require("michael.plugins.plugins-manager")
require("michael.plugins.whichkey")
require("michael.core.options")
require("michael.plugins.lualine")
require("michael.plugins.treesitter")
require("michael.plugins.nvim-tree")
require("michael.plugins.conform")
require("michael.plugins.mason")
